[package]
name = "zee-core"
version = "0.0.2"
edition = "2021"

[dependencies]
anyhow        = { workspace = true }
serde         = { workspace = true }
toml          = "0.8"
toml-span     = { workspace = true }
regex         = { workspace = true }
aho-corasick  = { workspace = true }
unicode-width = { workspace = true }
encoding_rs   = { workspace = true }
ropey         = { workspace = true }
rayon         = { workspace = true }
serde_json    = { workspace = true }
wasmi         = { workspace = true }
